name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          cd test
          gcc ../src/satcat.c ../src/satcat_code.c test.c -lm -ansi -I../src -o bin
